[build]
builder = "nixpacks"
watchPatterns = ["pipeline/**"]

[deploy]
startCommand = "cd pipeline && pip install -r requirements.txt && python main.py"
restartPolicyType = "on_failure"
cronSchedule = "0 14 * * *"
